spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todo_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: ollie123
  # 开发环境自动执行建表 SQL
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
